### ISSUE TITLE
Fix Chocolatey deploy

### ISSUE THREAD

**Issue by jathak** [google/dart_cli_pkg#49]

**Comment by nex3** [comment]
For context: `choco push` was failing for indeterminate reasons (see [this Travis log](https://travis-ci.org/github/sass/dart-sass/jobs/652706241), or the [raw log here](https://github.com/google/dart_cli_pkg/files/5024112/log.txt)). Unfortunately due to COVID-19 I don't have access to a Windows dev machine to debug this on, so until then (or until someone else can dive in and debug) we can't deploy to Chocolatey.
